# -*- coding: utf-8 -*-
"""English_to_Hinglish.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pxo-aRbdtkJJ-NqUcsOjw1ceBMnMKGGt
"""

pip install transformers

!pip install -qU \
  transformers \
  sentence-transformers\
  accelerate\
  einops \
  langchain \
  xformers \
  bitsandbytes

from transformers import pipeline

!pip install sentencepiece

!pip install transformers[sentencepiece]

# Create a translation pipeline for English to Hindi
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-hi")

translation_dict = {
    "प्रतिक्रिया": "feedback",
    "टिप्पणी": "comment",
    "खण्ड": "section",
    "वीडियो": "video",
    "उत्पादों": "products",
    "मिनट": "minute",
    "डेमो": "demo",
    "सिरसेट":"headset",
    "बैग": "bag"
}

# Input English text
english_text = input()
# Translate English text to Hinglish
hinglish_text = translator(english_text, max_length=100)[0]['translation_text']
words=hinglish_text.split(' ')
sentence=""
for word in words:
  if word in translation_dict:
    word=translation_dict[word]
    sentence+=" "+word
  else:
    sentence+=" "+word
print(sentence)